---
# CoreDNS Add-on
apiVersion: eks.services.k8s.aws/v1alpha1
kind: Addon
metadata:
  name: coredns-1111
  namespace: ack-system
  annotations:
    services.k8s.aws/region: us-west-1
    argocd.argoproj.io/sync-options: IgnoreExtraneous=true
spec:
  name: coredns
  clusterName: eksclusterhybrid-1111
  addonName: coredns
  resolveConflicts: OVERWRITE

---
# Kube-proxy Add-on
apiVersion: eks.services.k8s.aws/v1alpha1
kind: Addon
metadata:
  name: kube-proxy-1111
  namespace: ack-system
  annotations:
    services.k8s.aws/region: us-west-1
    argocd.argoproj.io/sync-options: IgnoreExtraneous=true
spec:
  name: kube-proxy
  clusterName: eksclusterhybrid-1111
  addonName: kube-proxy
  resolveConflicts: OVERWRITE
