apiVersion: kro.run/v1alpha1
kind: EKSClusterHybrid
metadata:
  name: eksclusterhybrid-2000
  namespace: kro-system
spec:
  clusterName: eksclusterhybrid-2000
  region: us-west-2
  vpcCIDR: "11.10.0.0/16"
  kubernetesVersion: "1.35"
  clusterRoleARN: "arn:aws:iam::242201304709:role/eksClusterRole"
  endpointPublicAccess: true
  endpointPrivateAccess: true
  # Hybrid node configuration
  remoteNodeCIDR: "192.168.10.0/24"
  remotePodCIDR: "192.168.11.0/24"
  # Subnet CIDRs (must be within VPC CIDR)
  publicSubnet1CIDR: "11.10.0.0/24"
  publicSubnet2CIDR: "11.10.1.0/24"
  privateSubnet1CIDR: "11.10.10.0/24"
  privateSubnet2CIDR: "11.10.11.0/24"
