{{- range $clusterName, $cluster := .Values.workloadClusters }}
{{- $wlRegion := default $.Values.aws.region (dig "aws" "region" "" $cluster) }}
{{- $wlAccountId := default $.Values.aws.accountId (dig "aws" "accountId" "" $cluster) }}
{{- range $i, $principal := $.Values.accessEntries.adminPrincipals }}
---
apiVersion: eks.services.k8s.aws/v1alpha1
kind: AccessEntry
metadata:
  name: {{ $clusterName }}-admin-access-{{ $i }}
  namespace: default
  annotations:
    services.k8s.aws/region: {{ $wlRegion }}
    services.k8s.aws/owner-account-id: "{{ $wlAccountId }}"
spec:
  clusterName: {{ $clusterName }}
  principalARN: {{ $principal }}
  type: STANDARD
  accessPolicies:
    - policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
      accessScope:
        type: cluster
{{- end }}
{{- end }}
