apiVersion: kro.run/v1alpha1
kind: EKSClusterHybrid
metadata:
  name: site-3000-useast1
  namespace: kro-system
spec:
  clusterName: site-3000-useast1
  region: us-east-1
  vpcCIDR: "11.20.0.0/16"
  kubernetesVersion: "1.35"
  clusterRoleARN: "arn:aws:iam::242201304709:role/eksClusterRole"
  cloudwatchRoleARN: "arn:aws:iam::242201304709:role/EKSCloudWatchObservabilityRole"
  endpointPublicAccess: true
  endpointPrivateAccess: true
  # Hybrid node configuration
  remoteNodeCIDR: "172.31.4.0/24"
  remotePodCIDR: "172.31.5.0/24"
  # Subnet CIDRs (must be within VPC CIDR)
  publicSubnet1CIDR: "11.20.0.0/24"
  publicSubnet2CIDR: "11.20.1.0/24"
  privateSubnet1CIDR: "11.20.10.0/24"
  privateSubnet2CIDR: "11.20.11.0/24"
